-- 대상자 개인정보 접근 로그 테이블
-- 목적: 누가/언제/왜 개인정보를 열람했는지 기록
-- 실행 위치: Supabase SQL Editor

create table if not exists public.client_access_logs (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.clients(id) on delete cascade,
  admin_id uuid references public.admins(id) on delete set null,
  admin_email text,
  access_action text not null check (access_action in ('name_unmask', 'details_view')),
  access_reason text not null,
  viewed_fields text[] not null default '{}'::text[],
  created_at timestamptz not null default now()
);

create index if not exists client_access_logs_client_id_idx
  on public.client_access_logs (client_id, created_at desc);

create index if not exists client_access_logs_created_at_idx
  on public.client_access_logs (created_at desc);

create index if not exists client_access_logs_admin_email_idx
  on public.client_access_logs (admin_email);

alter table public.client_access_logs enable row level security;

drop policy if exists client_access_logs_service_role_all on public.client_access_logs;
create policy client_access_logs_service_role_all
on public.client_access_logs
for all
to public
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

-- 확인용 조회
-- select * from public.client_access_logs order by created_at desc limit 50;
